name: Hello World
on: workflow_dispach # Triggering workflow manually
jobs:
    hello:
        runs_on: ubuntu-latest
        steps: 
            -name: Hello step
             run: echo "Hello welcome to Github Actions"