name: variables_and_secrets

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Build the project
        run: echo "Hey the project is build by ${{ vars.MY_NAME }}"
